config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users, controllers: {registrations: "registrations"}
  get "role", to: "pages#role"

  resources :articles

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  belongs_to :user
end

app/models/concerns/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :admin

  attr_writer :login

  validate :validate_username

  validate :password_complexity

  validates :username, format: { without: /\s/ }

  def login

    @login || self.username || self.email

  end

  def self.find_for_database_authentication(warden_conditions)

    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase}]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)

      where(conditions.to_h).first

    end

  end

  def validate_username

    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end

  end


  def password_complexity
    if password.present? and not password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)./)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
    end
  end


  # def password_complexity
  #   if password.present?
  #     if !password.match(/^(?=.*[a-z])(?=.*[A-Z])/)
  #       errors.add :password, "complexity requirement not met"
  #     end
  #   end
  # end

  # def username
  #
  #   return self.email.split('@')[0].capitalize
  #
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  attr_accessor :user

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def role
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def admin
    current_user.admin == TRUE
  end

  def regular_user
    current_user.admin == FALSE
  end

  protected

  def after_sign_up_path_for(resource)
    '/role'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>
<br>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>
<strong> Articles </strong>
</h1>


<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
    <br>
  <% end %>
</ul>

<%= link_to "Back", '/' %> |
<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<br>
<%= render 'form', article: @article %>
<br>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>
  <strong>Title:</strong>
  <%= @article.title %>
</h1>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user.email %>
</p>


<%= link_to 'Back', articles_path %>
<% if @article.user == current_user %> |
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to "Destroy", article_path(@article),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<% end %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<head>
  <%name = current_user.present? ? current_user.username : 'New guest ' %>

  <h1>
    <strong>  Welcome, <%=name %>  </strong>
  </h1>
  <br>
  <h2>
  <%= link_to 'Articles', articles_path %>
  </h2>
  <br>
</head>

<body>
<% if current_user %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %> |
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %> |
  <%= link_to 'Log in', new_user_session_path %>
<% end %>

<% if user_signed_in? %>
  <%= link_to 'Account Setting', edit_user_registration_path %>
<% end %>
</body>

app/views/pages/role.html.erb
<p>
  <strong>Choose Role:</strong>
<%= button_to "Admin", root_path,:method=>:get %>
  <br>
<%= button_to "User",  root_path,:method=>:get %>
</p>